### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrTob** [vvidday/repo-watch#10]
First of all, congratulations on winning the category "Best Realtime Project".🎉🥳

While looking at the source code, a question came up.
Can you explain me how to call the edge functions using pg_cron. I don't really understand that yet. ❓

**Comment by vvidday** [comment]
Thanks @MrTob! For calling edge functions, here's a [guide](https://supabase.com/docs/guides/database/extensions/http) by supabase on the topic - essentially, you can install a postgres plugin that allows you to make HTTP requests from the postgres server. Hope this helps!

**Comment by MrTob** [comment]
ok, that means i build a cron job that calls the endpoint from the edge function.
 there i also have to do the authentication.  whats' the right way?
post the header to the http request?
how did you solve this, can you see the code?

**Comment by vvidday** [comment]
Yup, something like this:
```
select 
  cron.schedule (
    'poll-and-revalidate',
    '* * * * *',
    $$
	select status
  		from http((
    		'POST',
    		'https://xxx.functions.supabase.co/yyy',
    		array[http_header('Authorization', 'Bearer zzz')],
      		'application/json',
		NULL
    	)::http_request))
    $$  
  );
```
You can find the documentation [here](https://github.com/pramsey/pgsql-http#concepts)

**Comment by MrTob** [comment]
thx
