### ISSUE TITLE
dark mode issue

### ISSUE THREAD

**Issue by andriusmv** [vvidday/repo-watch#8]
![Captura de pantalla (380)](https://user-images.githubusercontent.com/99091918/186754701-1eb4adc5-1969-4438-9169-8311b8b3ad24.png)

dark mode not working. seems to be default to System? couldn't find a dark/light mode button.

great project guys! inspiring af!

AM

**Comment by vvidday** [comment]
Thanks for reporting this @andriusmv! The issue should hopefully be fixed by #9 - do let me know if there's any further issues!
